import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: ["class", '[data-color-mode="dark"]'],
  theme: {
    extend: {
      colors: {
        // ABYSS Theme (深海) - 使用 CSS 變數支援日夜模式
        abyss: {
          black: "var(--abyss-black, #000205)",
          cyan: "var(--abyss-cyan, #00ffff)",
          purple: "#7b00ff",
          glass: "rgba(0, 5, 10, 0.6)",
          bg: "var(--abyss-bg, #000205)",
          surface: "var(--abyss-surface, #050a14)",
          text: "var(--abyss-text, #e0f7fa)",
          muted: "var(--abyss-muted, #80deea)",
          "text-dim": "var(--abyss-muted, #80deea)",
          accent: "var(--abyss-cyan, #00ffff)",
        },
        // PRISM Theme (水晶) - 使用 CSS 變數支援日夜模式
        prism: {
          void: "var(--prism-void, #0b001a)",
          purple: "var(--prism-purple, #b388ff)",
          blue: "#82b1ff",
          accent: "var(--prism-accent, #b388ff)",
          glass: "rgba(255, 255, 255, 0.05)",
          bg: "var(--prism-bg, #0b001a)",
          surface: "var(--prism-surface, #150030)",
          text: "var(--prism-text, #ffffff)",
          muted: "var(--prism-muted, #aaaaaa)",
          "text-dim": "var(--prism-muted, #aaaaaa)",
        },
        // LUXE Theme (高端) - 使用 CSS 變數支援日夜模式
        luxe: {
          black: "var(--luxe-black, #0a0a0a)",
          gold: "var(--luxe-gold, #d4af37)",
          "gold-dim": "var(--luxe-gold-dim, #8a7020)",
          bg: "var(--luxe-bg, #0a0a0a)",
          surface: "var(--luxe-surface, #141414)",
          text: "var(--luxe-text, #e0e0e0)",
          muted: "var(--luxe-muted, #888888)",
          "text-dim": "var(--luxe-muted, #888888)",
          accent: "var(--luxe-gold, #d4af37)",
        },
      },
      fontFamily: {
        // 高端主題字體
        display: ["Playfair Display", "serif"],
        body: ["Lato", "sans-serif"],
        // 深海主題字體
        "abyss-title": ["Aboreto", "cursive"],
        "abyss-body": ["Montserrat", "sans-serif"],
        // 水晶主題字體
        "prism-title": ["Cinzel", "serif"],
        "prism-body": ["Raleway", "sans-serif"],
      },
      animation: {
        "fade-up": "fadeUp 1s ease forwards",
        "fade-in": "fadeIn 0.3s ease forwards",
        drift: "drift 20s linear infinite",
        "glow-pulse": "glowPulse 2s ease-in-out infinite",
      },
      keyframes: {
        fadeUp: {
          "0%": { opacity: "0", transform: "translateY(30px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        drift: {
          "0%": { backgroundPosition: "0 0" },
          "100%": { backgroundPosition: "0 100px" },
        },
        glowPulse: {
          "0%, 100%": { boxShadow: "0 0 20px rgba(0, 255, 255, 0.3)" },
          "50%": { boxShadow: "0 0 40px rgba(0, 255, 255, 0.6)" },
        },
      },
      backdropBlur: {
        xs: "2px",
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        abyss: {
          primary: "#00ffff",
          secondary: "#7b00ff",
          accent: "#00ffff",
          neutral: "#000205",
          "base-100": "#000205",
          "base-200": "#050a14",
          "base-300": "#0a1428",
          "base-content": "#e0f7fa",
          info: "#00ffff",
          success: "#36D399",
          warning: "#FBBD23",
          error: "#F87272",
          "--abyss-bg": "#000205",
          "--abyss-surface": "#050a14",
          "--abyss-text": "#e0f7fa",
          "--abyss-muted": "#80deea",
        },
        prism: {
          primary: "#b388ff",
          secondary: "#82b1ff",
          accent: "#b388ff",
          neutral: "#0b001a",
          "base-100": "#0b001a",
          "base-200": "#150030",
          "base-300": "#200050",
          "base-content": "#ffffff",
          info: "#82b1ff",
          success: "#36D399",
          warning: "#FBBD23",
          error: "#F87272",
          "--prism-bg": "#0b001a",
          "--prism-surface": "#150030",
          "--prism-text": "#ffffff",
          "--prism-muted": "#aaaaaa",
        },
        luxe: {
          primary: "#d4af37",
          secondary: "#8a7020",
          accent: "#d4af37",
          neutral: "#0a0a0a",
          "base-100": "#0a0a0a",
          "base-200": "#141414",
          "base-300": "#1e1e1e",
          "base-content": "#e0e0e0",
          info: "#d4af37",
          success: "#36D399",
          warning: "#FBBD23",
          error: "#F87272",
          "--luxe-bg": "#0a0a0a",
          "--luxe-surface": "#141414",
          "--luxe-text": "#e0e0e0",
          "--luxe-muted": "#888888",
        },
        // 亮色主題 - 需要深色文字
        "luxe-light": {
          primary: "#b8962b",
          secondary: "#6a5515",
          accent: "#b8962b",
          neutral: "#f5f5f5",
          "base-100": "#ffffff",
          "base-200": "#f8f8f8",
          "base-300": "#eeeeee",
          "base-content": "#1a1a1a",
          info: "#b8962b",
          success: "#059669",
          warning: "#d97706",
          error: "#dc2626",
          "--luxe-bg": "#ffffff",
          "--luxe-surface": "#f8f8f8",
          "--luxe-text": "#1a1a1a",
          "--luxe-muted": "#555555",
        },
        "abyss-light": {
          primary: "#00b3b3",
          secondary: "#5500cc",
          accent: "#00b3b3",
          neutral: "#f0f9fa",
          "base-100": "#ffffff",
          "base-200": "#e8f5f7",
          "base-300": "#d0ebef",
          "base-content": "#0a1a1a",
          info: "#00b3b3",
          success: "#059669",
          warning: "#d97706",
          error: "#dc2626",
          "--abyss-bg": "#ffffff",
          "--abyss-surface": "#e8f5f7",
          "--abyss-text": "#0a1a1a",
          "--abyss-muted": "#4a5568",
        },
        "prism-light": {
          primary: "#7c4dff",
          secondary: "#448aff",
          accent: "#7c4dff",
          neutral: "#f5f0ff",
          "base-100": "#ffffff",
          "base-200": "#f8f5ff",
          "base-300": "#efe8ff",
          "base-content": "#1a0a30",
          info: "#448aff",
          success: "#059669",
          warning: "#d97706",
          error: "#dc2626",
          "--prism-bg": "#ffffff",
          "--prism-surface": "#f8f5ff",
          "--prism-text": "#1a0a30",
          "--prism-muted": "#5a4a6a",
        },
      },
    ],
  },
};

export default config;
